version: '2'

services:
  db:
    image: postgres:9.6.2
  web:
    build: ./perma-payments
    image: perma-payments:0.24
    tty: true
    command: bash
    volumes:
      - ./perma-payments:/perma-payments
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - db
