version: '2'

services:
  pp-db:
    image: registry.lil.tools/library/postgres:12.11
    volumes:
      - db_data_12:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_PASSWORD=example
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: registry.lil.tools/harvardlil/perma-payments:4-0713c04cf39c839d249be111ebc30b36
    tty: true
    command: bash
    environment:
      - DOCKERIZED=true
    volumes:
      - .:/app:delegated
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - pp-db
    networks:
      default:
        aliases:
          - 'perma-payments'

volumes:
  db_data_12:

networks:
  default:
