# overrides for local development, not used in CI
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/perma-payments:17-cef860948eab13a44deb5600bac2806c
        platforms:
          - linux/amd64
          - linux/arm64
      x-hash-paths:
        - web/requirements.txt
