version: '2'

services:
  db:
    image: registry.lil.tools/library/postgres:9.6.2
    volumes:
      - db_data:/var/lib/postgresql/data:delegated
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: registry.lil.tools/harvardlil/perma-payments:0.32
    tty: true
    command: bash
    environment:
      - DOCKERIZED=true
    volumes:
      - .:/app:delegated
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - db

volumes:
  db_data:
