# overrides for local development, not used in CI
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/perma-payments:5-7dd86582d03f665417a524c226877184
        platforms:
          - linux/amd64
          - linux/arm64
      x-hash-paths:
        - web/requirements.txt
