# overrides for local development, not used in CI
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/perma-payments:6-fc3e7a41c2c4ab7dd526cacb63a64e78
        platforms:
          - linux/amd64
          - linux/arm64
      x-hash-paths:
        - web/requirements.txt
