name: Lints

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Flake8
        run: |
          pip install `egrep -o 'flake8==\S+' web/requirements.txt`  # install our version of flake8
          # suppress this until we've actually made the codebase pass...
          # flake8 web/
